dino:
  head_n_prototypes: 8192
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 8192
train:
  batch_size_per_gpu: 16
  dataset_path: '../../../DINO_Dataset_1024'
  centering: sinkhorn_knopp
  OFFICIAL_EPOCH_LENGTH: 1000
  num_workers: 8
student:
  arch: vit_base
  patch_size: 14
  drop_path_rate: 0.2
  ffn_layer: mlp
  block_chunks: 0
  num_register_tokens: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 100
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 20
  layerwise_decay: 1.0
evaluation:
  eval_period_iterations: 100
crops:
  global_crops_size: 518
  local_crops_size: 210
