dino:
  head_n_prototypes: 2048
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 2048
train:
  batch_size_per_gpu: 16
  dataset_path: '../../../SSL_Training_Dataset_1024'
  centering: sinkhorn_knopp
student:
  arch: vit_large
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: mlp
  block_chunks: 0
  num_register_tokens: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 500
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 20
  layerwise_decay: 1.0
evaluation:
  eval_period_iterations: 200
crops:
  global_crops_size: 518
  local_crops_size: 210
